# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5c05ca4c9d1e5c7ad32fa2965f7cb1757d2ef7ea4dd082701cca083d8bba20e70d4456efd499ba3c38297961273bceaa78a993e3c9c1aa2dc7b99c23764dec2

test:
  secret_key_base: 43b6a7b9461251f9254c9b22c71d96e4cf5e963a5854f15fac16b5d8ca0a1c81b9cc11e25e1e2661ef76c7be9d68b1a58e3f737e48d6f95ef1693ac8d35db3cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
